[features]
seeds = false
skip-lint = false
[programs.localnet]
tokenplex_exchange = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://rpc-devnet.helius.xyz/?api-key=69bea66a-a716-416b-8a45-a9c7049b0731"


[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# test = "yarn run ts-mocha -n loader=ts-node/esm -p ./tsconfig.json -t 1000000 tests/**/*.ts"
